### ISSUE TITLE
build-args only supports single ARG

### ISSUE THREAD

**Issue by jherrerasbp** [schubergphilis/mcvs-docker-action#123]
The `build-args` has `APPLICATION` arg [hardcoded](https://github.com/schubergphilis/mcvs-docker-action/blob/d27e0d28d73b0cd6924bca616e159bb6a00c6e79/action.yml#L70). 

```yaml
    - name: Build an image from a dockerfile
      uses: docker/build-push-action@v6.18.0
      with:
        build-args: APPLICATION=${{ inputs.build-args }}
        context: ${{ inputs.context }}
        labels: ${{ steps.meta.outputs.labels }}
        push: false
        tags: ${{ steps.meta.outputs.tags }}
```

This is a problem when the Dockerfile has multiple `ARG` because then is not possible to use them in this step, e.g.: 

`Dockerfile`
```Dockerfile
ARG APPLICATION=mcvs-scanner \
    APPLICATION_PERMISSIONS=0700 \
    APPLICATION_USER_ID=1000 \
    PROJECT_KEY
```
