### ISSUE TITLE
PoLP

### ISSUE THREAD

**Issue by sbp-bvanb** [schubergphilis/mcvs-docker-action#16]
```
jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      #
    steps:
```
